import os
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from models.schemas import (
    Token,
    UserInDB,
    UserCreate,
    UserOut,
    TokenData,
    ChangePasswordRequest,
    UpdateUserRoleRequest,
    UpdateUserStatusRequest
)
from core.security import verify_password, create_access_token, get_password_hash
from database import get_db_pool
from dependencies.auth_dependency import get_current_user, RoleChecker
import oracledb

router = APIRouter(prefix="/auth", tags=["Authentication"])

def get_user_from_db(username: str):
    """Fetch user from the database by username."""
    pool = get_db_pool()
    with pool.get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT user_id, username, hashed_password, role, is_active, created_at, doctor_id FROM users WHERE username = :1",
                [username]
            )
            row = cursor.fetchone()
            if row:
                return UserInDB(
                    user_id=row[0],
                    username=row[1],
                    hashed_password=row[2],
                    role=row[3],
                    is_active=bool(row[4]),
                    created_at=row[5],
                    doctor_id=row[6]
                )
    return None

def create_users_table_if_not_exists():
    """Create the users table if it does not exist in the database."""
    pool = get_db_pool()
    try:
        with pool.get_connection() as conn:
            with conn.cursor() as cursor:
                try:
                    cursor.execute("SELECT 1 FROM users FETCH FIRST 1 ROWS ONLY")
                    # Table exists, check if doctor_id column exists
                    try:
                        cursor.execute("SELECT doctor_id FROM users FETCH FIRST 1 ROWS ONLY")
                    except oracledb.DatabaseError as ex:
                        err = ex.args[0]
                        if err.code == 904: # Column does not exist
                            print("Column 'doctor_id' does not exist in 'users' table. Altering table...")
                            cursor.execute("ALTER TABLE users ADD doctor_id NUMBER")
                            cursor.execute("ALTER TABLE users ADD CONSTRAINT fk_user_doctor FOREIGN KEY (doctor_id) REFERENCES DOCTOR(doctor_id) ON DELETE SET NULL")
                            conn.commit()
                            print("Column 'doctor_id' added successfully.")
                        else:
                            raise
                except oracledb.DatabaseError as e:
                    error_obj = e.args[0]
                    # ORA-00942: table or view does not exist
                    if error_obj.code == 942:
                        print("Table 'users' does not exist. Creating table 'users'...")
                        cursor.execute("""
                            CREATE TABLE users (
                                user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                username VARCHAR2(50) UNIQUE NOT NULL,
                                hashed_password VARCHAR2(255) NOT NULL,
                                role VARCHAR2(20) NOT NULL CHECK (role IN ('RECEPTIONIST', 'DOCTOR', 'PHARMACIST', 'ADMIN')),
                                is_active NUMBER(1) DEFAULT 1 NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                doctor_id NUMBER,
                                CONSTRAINT fk_user_doctor FOREIGN KEY (doctor_id) REFERENCES DOCTOR(doctor_id) ON DELETE SET NULL
                            )
                        """)
                        conn.commit()
                        print("Table 'users' created successfully.")
                    else:
                        raise
    except Exception as e:
        print(f"Error checking/creating users table: {str(e)}")

def seed_admin_user():
    """Seed default admin user if it does not exist."""
    create_users_table_if_not_exists()
    pool = get_db_pool()
    try:
        with pool.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("SELECT COUNT(*) FROM users WHERE username = :1", ["admin"])
                count = cursor.fetchone()[0]
                if count == 0:
                    default_pwd = os.getenv("DEFAULT_ADMIN_PASSWORD", "admin123")
                    hashed_pwd = get_password_hash(default_pwd)
                    cursor.execute(
                        "INSERT INTO users (username, hashed_password, role, is_active) VALUES (:1, :2, :3, :4)",
                        ["admin", hashed_pwd, "ADMIN", 1]
                    )
                    conn.commit()
                    print("Seeded default admin user with username: 'admin'")
    except Exception as e:
        print(f"Error seeding admin user: {str(e)}")

@router.post("/token", response_model=Token)
def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends()):
    # 1. Fetch user from DB
    user = get_user_from_db(form_data.username)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    # 2. Verify Password
    if not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # 3. Check if user is active
    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User account is deactivated. Please contact an administrator.",
        )

    # 4. Create JWT Token (include role and doctor_id inside it)
    access_token = create_access_token(
        data={"sub": user.username, "role": user.role, "doctor_id": user.doctor_id}
    )
    
    return {"access_token": access_token, "token_type": "bearer"}

@router.post("/register", response_model=UserOut)
def register_user(
    user_in: UserCreate,
    current_user: TokenData = Depends(RoleChecker(["ADMIN"]))
):
    """Admin registers a new user."""
    existing_user = get_user_from_db(user_in.username)
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username already exists"
        )
    
    # Only allow doctor_id for users of role DOCTOR
    doc_id = user_in.doctor_id if user_in.role == "DOCTOR" else None
    
    hashed_pwd = get_password_hash(user_in.password)
    pool = get_db_pool()
    try:
        with pool.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO users (username, hashed_password, role, is_active, doctor_id) VALUES (:1, :2, :3, :4, :5)",
                    [user_in.username, hashed_pwd, user_in.role, 1 if user_in.is_active else 0, doc_id]
                )
                conn.commit()
    except oracledb.DatabaseError as e:
        error_obj = e.args[0]
        # ORA-02291: integrity constraint violated - parent key not found (foreign key to DOCTOR)
        if error_obj.code == 2291:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Selected Doctor ID {doc_id} does not exist in the Doctor records."
            )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database error during registration: {str(e)}"
        )
            
    new_user = get_user_from_db(user_in.username)
    if not new_user:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve registered user"
        )
        
    return UserOut(
        user_id=new_user.user_id,
        username=new_user.username,
        role=new_user.role,
        is_active=new_user.is_active,
        created_at=new_user.created_at,
        doctor_id=new_user.doctor_id
    )

@router.post("/change-password")
def change_password(
    request: ChangePasswordRequest,
    current_user: TokenData = Depends(get_current_user)
):
    """User changes their own password by verifying the old password."""
    user = get_user_from_db(current_user.username)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
        
    if not verify_password(request.old_password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Incorrect old password"
        )
        
    new_hashed_pwd = get_password_hash(request.new_password)
    pool = get_db_pool()
    with pool.get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "UPDATE users SET hashed_password = :1 WHERE username = :2",
                [new_hashed_pwd, current_user.username]
            )
            conn.commit()
            
    return {"message": "Password changed successfully"}

@router.put("/users/{username}/status", response_model=UserOut)
def update_user_status(
    username: str,
    status_update: UpdateUserStatusRequest,
    current_user: TokenData = Depends(RoleChecker(["ADMIN"]))
):
    """Admin deactivates or activates a user. Prevents self-deactivation."""
    if username == current_user.username and not status_update.is_active:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Admin cannot deactivate their own account"
        )
        
    user = get_user_from_db(username)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
        
    pool = get_db_pool()
    with pool.get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "UPDATE users SET is_active = :1 WHERE username = :2",
                [1 if status_update.is_active else 0, username]
            )
            conn.commit()
            
    updated_user = get_user_from_db(username)
    return UserOut(
        user_id=updated_user.user_id,
        username=updated_user.username,
        role=updated_user.role,
        is_active=updated_user.is_active,
        created_at=updated_user.created_at,
        doctor_id=updated_user.doctor_id
    )

@router.put("/users/{username}/role", response_model=UserOut)
def update_user_role(
    username: str,
    role_update: UpdateUserRoleRequest,
    current_user: TokenData = Depends(RoleChecker(["ADMIN"]))
):
    """Admin updates any user's role."""
    user = get_user_from_db(username)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found"
        )
        
    pool = get_db_pool()
    with pool.get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "UPDATE users SET role = :1 WHERE username = :2",
                [role_update.role, username]
            )
            conn.commit()
            
    updated_user = get_user_from_db(username)
    return UserOut(
        user_id=updated_user.user_id,
        username=updated_user.username,
        role=updated_user.role,
        is_active=updated_user.is_active,
        created_at=updated_user.created_at,
        doctor_id=updated_user.doctor_id
    )

@router.get("/users", response_model=List[UserOut])
def list_users(current_user: TokenData = Depends(RoleChecker(["ADMIN"]))):
    """Admin retrieves a list of all users."""
    pool = get_db_pool()
    users_list = []
    with pool.get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT user_id, username, role, is_active, created_at, doctor_id FROM users ORDER BY username"
            )
            for row in cursor.fetchall():
                users_list.append(
                    UserOut(
                        user_id=row[0],
                        username=row[1],
                        role=row[2],
                        is_active=bool(row[3]),
                        created_at=row[4],
                        doctor_id=row[5]
                    )
                )
    return users_list